/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SOILMETER_SRC_SOIL_METER_PB_H_INCLUDED
#define PB_SOILMETER_SRC_SOIL_METER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _soilmeter_SoilUpdate {
    char meter_name[40];
    float temperature;
    uint32_t soil_moisture;
} soilmeter_SoilUpdate;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define soilmeter_SoilUpdate_init_default        {"", 0, 0}
#define soilmeter_SoilUpdate_init_zero           {"", 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define soilmeter_SoilUpdate_meter_name_tag      1
#define soilmeter_SoilUpdate_temperature_tag     2
#define soilmeter_SoilUpdate_soil_moisture_tag   3

/* Struct field encoding specification for nanopb */
#define soilmeter_SoilUpdate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   meter_name,        1) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       2) \
X(a, STATIC,   SINGULAR, UINT32,   soil_moisture,     3)
#define soilmeter_SoilUpdate_CALLBACK NULL
#define soilmeter_SoilUpdate_DEFAULT NULL

extern const pb_msgdesc_t soilmeter_SoilUpdate_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define soilmeter_SoilUpdate_fields &soilmeter_SoilUpdate_msg

/* Maximum encoded size of messages (where known) */
#define SOILMETER_SRC_SOIL_METER_PB_H_MAX_SIZE   soilmeter_SoilUpdate_size
#define soilmeter_SoilUpdate_size                52

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
